### ISSUE TITLE
The typo ‘week’ occurs twice.

### ISSUE THREAD

**Issue by jmarkmorris** [NoamWhy/UCV#1]
Search on the text 'week' in the original document will locate two typos that should be 'weak'.

**Comment by NoamWhy** [comment]
Thanks a lot, Mark, I have submitted a new corrected version (2021-01-25). 
There was also a minor error in equations (3.2-1) and (3.2-4).
Unfortunately, this error appears also in the YouTube video, but I can't fix that.

Thanks again for your wonderful contribution to UCV theory!
